package Vista;

import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Santiago
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenu
     */
    public VistaMenuPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    public JMenuItem getMnSalir() {
        return mnSalir;
    }

    public void setMnSalir(JMenuItem mnSalir) {
        this.mnSalir = mnSalir;
    }


    public JLabel getLblNombre() {
        return lblNombre;
    }

    public JButton getBtnV2() {
        return btnV2;
    }

    public void setBtnV2(JButton btnV2) {
        this.btnV2 = btnV2;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    public JLabel getLblTipoUsuario() {
        return lblTipoUsuario;
    }

    public void setLblTipoUsuario(JLabel lblTipoUsuario) {
        this.lblTipoUsuario = lblTipoUsuario;
    }

    public JButton getBtnAdminPersonal() {
        return btnAdminPersonal;
    }

    public void setBtnAdminPersonal(JButton btnAdminPersonal) {
        this.btnAdminPersonal = btnAdminPersonal;
    }

    public JButton getBtnAdminProductos() {
        return btnAdminProductos;
    }

    public void setBtnAdminProductos(JButton btnAdminProductos) {
        this.btnAdminProductos = btnAdminProductos;
    }

    public JButton getBtnRegistrarClientes() {
        return btnRegistrarClientes;
    }

    public void setBtnRegistrarClientes(JButton btnRegistrarClientes) {
        this.btnRegistrarClientes = btnRegistrarClientes;
    }

    public JButton getBtnReportes() {
        return btnReportes;
    }

    public void setBtnReportes(JButton btnReportes) {
        this.btnReportes = btnReportes;
    }

    public JButton getBtnVentas() {
        return btnVentas;
    }

    public void setBtnVentas(JButton btnVentas) {
        this.btnVentas = btnVentas;
    }

    public JDesktopPane getjDeskPanel() {
        return jDeskPanel;
    }

    public void setjDeskPanel(JDesktopPane jDeskPanel) {
        this.jDeskPanel = jDeskPanel;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return menuCrearUsuarios;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.menuCrearUsuarios = jMenu2;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public JMenuItem getMenuRegAdministrador() {
        return menuRegAdministrador;
    }

    public void setMenuRegAdministrador(JMenuItem menuRegAdministrador) {
        this.menuRegAdministrador = menuRegAdministrador;
    }

    public JMenuItem getMenuRegUsuario() {
        return menuRegUsuario;
    }

    public void setMenuRegUsuario(JMenuItem menuRegUsuario) {
        this.menuRegUsuario = menuRegUsuario;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }

    public JMenu getMenuCrearUsuarios() {
        return menuCrearUsuarios;
    }

    public void setMenuCrearUsuarios(JMenu menuCrearUsuarios) {
        this.menuCrearUsuarios = menuCrearUsuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAdminProductos = new javax.swing.JButton();
        btnAdminPersonal = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnRegistrarClientes = new javax.swing.JButton();
        btnV2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jDeskPanel = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCrearUsuarios = new javax.swing.JMenu();
        menuRegUsuario = new javax.swing.JMenuItem();
        menuRegAdministrador = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 107, 179));

        jLabel3.setText("Usuario Registrado:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTipoUsuario.setText("Admin");

        lblNombre.setText("Joaquin Ortega");
        lblNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(416, Short.MAX_VALUE)
                .addComponent(lblNombre)
                .addGap(185, 185, 185)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addComponent(lblTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoUsuario)
                    .addComponent(jLabel3)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 107, 179));

        jLabel5.setText("Dirección:");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Av. Don Bosco y Av. Loja");

        jLabel8.setText("Télefonos:");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("0985487758 - 4135687");

        jLabel2.setText("Software 1.0");

        jLabel1.setText("Helados \"La Tienda\"");

        btnAdminProductos.setText("APR");
        btnAdminProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminProductosActionPerformed(evt);
            }
        });

        btnAdminPersonal.setText("APE");

        btnVentas.setText("VNT");

        btnReportes.setText("RPT");

        btnRegistrarClientes.setText("RCL");

        btnV2.setText("V2");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnAdminProductos))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnAdminPersonal))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnVentas))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnReportes))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnRegistrarClientes))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnV2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel5))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel8))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnAdminProductos)
                .addGap(28, 28, 28)
                .addComponent(btnAdminPersonal)
                .addGap(18, 18, 18)
                .addComponent(btnVentas)
                .addGap(8, 8, 8)
                .addComponent(btnReportes)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarClientes)
                .addGap(18, 18, 18)
                .addComponent(btnV2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDeskPanel.setBackground(new java.awt.Color(230, 245, 254));

        javax.swing.GroupLayout jDeskPanelLayout = new javax.swing.GroupLayout(jDeskPanel);
        jDeskPanel.setLayout(jDeskPanelLayout);
        jDeskPanelLayout.setHorizontalGroup(
            jDeskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDeskPanelLayout.setVerticalGroup(
            jDeskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("Productos");
        jMenuBar.add(jMenu1);

        menuCrearUsuarios.setText("Administrador");

        menuRegUsuario.setText("Registrar Usuario");
        menuCrearUsuarios.add(menuRegUsuario);

        menuRegAdministrador.setText("Registrar Administrador");
        menuCrearUsuarios.add(menuRegAdministrador);

        jMenuBar.add(menuCrearUsuarios);

        jMenu2.setText("Opciones");

        mnSalir.setText("Salir");
        jMenu2.add(mnSalir);

        jMenuBar.add(jMenu2);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDeskPanel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jDeskPanel))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminProductosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminPersonal;
    private javax.swing.JButton btnAdminProductos;
    private javax.swing.JButton btnRegistrarClientes;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnV2;
    private javax.swing.JButton btnVentas;
    private javax.swing.JDesktopPane jDeskPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JMenu menuCrearUsuarios;
    private javax.swing.JMenuItem menuRegAdministrador;
    private javax.swing.JMenuItem menuRegUsuario;
    private javax.swing.JMenuItem mnSalir;
    // End of variables declaration//GEN-END:variables
}
